import { NextResponse } from "next/server";
import { headers } from "next/headers";
import { z } from "zod";
import { auth } from "~/lib/auth";
import { db } from "~/server/db";
import { revalidatePath } from "next/cache";

const StaffSchema = z.object({
  name: z.string().min(1, "Nama tidak boleh kosong"),
  gender: z.enum(["MALE", "FEMALE"], {
    error: "Gender harus MALE atau FEMALE",
  }),
  role: z.string().min(1, "Jabatan tidak boleh kosong"),
  department: z.string().min(1, "Departemen wajib dipilih"),
  imageUrl: z.string().optional(),
  isActive: z.boolean().default(true),
});

export async function GET() {
  try {
    const session = await auth.api.getSession({
      headers: await headers(),
    });

    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const staff = await db.staff.findMany({
      orderBy: {
        order: "asc",
      },
    });

    return NextResponse.json(staff);
  } catch (error) {
    console.error("[STAFF_GET]", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 },
    );
  }
}

export async function POST(request: Request) {
  try {
    const session = await auth.api.getSession({
      headers: await headers(),
    });

    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = (await request.json()) as unknown;
    const validation = StaffSchema.safeParse(body);

    if (!validation.success) {
      return NextResponse.json(
        { error: "Data tidak valid", details: validation.error.format() },
        { status: 400 },
      );
    }

    const { name, gender, role, department, imageUrl, isActive } =
      validation.data;

    const lastStaff = await db.staff.findFirst({
      orderBy: { order: "desc" },
      select: { order: true },
    });

    const newOrder = (lastStaff?.order ?? -1) + 1;

    const autoGeneratedNip = `STAFF-${Date.now()}-${Math.floor(Math.random() * 1000)}`;

    const newStaff = await db.staff.create({
      data: {
        name,
        nip: autoGeneratedNip,
        gender,
        role,
        department,
        imageUrl,
        isActive,
        order: newOrder,
      },
    });

    revalidatePath("/about/staff-profile");

    return NextResponse.json(newStaff, { status: 201 });
  } catch (error) {
    console.error("[STAFF_POST]", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 },
    );
  }
}
